app/blueprints/seller/models.py
from app import db
import os 
import cloudinary
import cloudinary.uploader 
import cloudinary.api

cloudinary.config(
    cloud_name=os.environ.get('CLOUDINARY_NAME'),
    api_key=os.environ.get('CLOUDINARY_API_KEY'),
    api_secret=os.environ.get('CLOUDINARY_API_SECRET')
)

class Book(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(100))
    author = db.Column(db.String(50))
    desc = db.Column(db.String(10000))
    price = db.Column(db.Numeric(5, 2))
    image_url = db.Column(db.String(100))

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        db.session.add(self)
        db.session.commit()

    def update(self, **kwargs):
        for key, value in kwargs.items():
            if key in {'title', 'author', 'desc', 'price'}:
                setattr(self, key, value)
            db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __str__(self):
        return self.title

    def upload_to_cloudinary(self, file_to_upload):
        image_info = cloudinary.uploader.upload(file_to_upload)
        self.image_url = image_info.get('url')
        db.session.commit()

class BookList(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    seller_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    book_id = db.Column(db.Integer, db.ForeignKey('book.id'))

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        db.session.add(self)
        db.session.commit()

app/blueprints/shop/models.py
from app import db 

class Cart(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    book_id = db.Column(db.Integer, db.ForeignKey('book.id'))

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        db.session.add(self)
        db.session.commit()
    
    def delete(self):
        db.session.delete(self)
        db.session.commit()

app/blueprints/seller/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, DecimalField, SubmitField, FileField
from wtforms.validators import DataRequired 

class BookForm(FlaskForm):
    image = FileField('Book Image')
    title = StringField('Title', validators=[DataRequired()])
    author = StringField('Author', validators=[DataRequired()])
    desc = StringField('Description', validators=[DataRequired()])
    price = DecimalField('Price', places=2, validators=[DataRequired()])
    submit = SubmitField('Add')

app/__init__.py
from flask import Flask 
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate 
from flask_login import LoginManager 
from config import Config 

app = Flask(__name__)
app.config.from_object(Config)

db = SQLAlchemy(app)
migrate = Migrate(app, db, compare_type=True)

login = LoginManager(app)
login.login_view = 'auth.login'
login.login_message_category = 'danger'

from app.blueprints.auth import auth 
app.register_blueprint(auth)

from app.blueprints.shop import shop 
app.register_blueprint(shop)

from app.blueprints.seller import seller 
app.register_blueprint(seller)


from app import routes

app/blueprints/seller/__init__.py
from flask import Blueprint

seller = Blueprint('seller', __name__, url_prefix='/seller')

from . import routes, models

app/blueprints/seller/routes.py
from . import seller 
from flask import render_template, redirect, url_for, flash 
from flask_login import login_required, current_user
from .forms import BookForm
from .models import Book, BookList

@seller.route('/') 
def index():
    return redirect(url_for('shop.index'))

@seller.route('/upload-item', methods=['GET', 'POST'])
@login_required
def upload_item():
    title = "Upload Book For Sale"
    form = BookForm()

    if form.validate_on_submit():
        booktitle = form.title.data 
        author = form.author.data 
        desc = form.desc.data 
        price = form.price.data 
        image = form.image.data 

        new_book = Book(title = booktitle, author = author, desc = desc, price = price)
        if image: 
            new_book.upload_to_cloudinary(image)
        
        seller_id = current_user.id 
        book_id = new_book.id

        new_book_list = BookList(seller_id = seller_id, book_id = book_id)

        flash(f"{booktitle} has been added to your Store.", "primary")
        return redirect(url_for('shop.index'))

    return render_template('upload_item.html', title=title, form=form)

@seller.route('/view-listings')
@login_required 
def view_listing():
    title = 'View My Listings'
    user_cart = ""
    books = [Book.query.filter(Book.id == cart.book_id).all()[0] for cart in current_user.my_listings.all()]
    total = sum([book.price for book in books])

    if books:
        cart = current_user.my_listings.all()
        user_cart = zip(books, cart)

    return render_template('view_listing.html', title=title, user_cart = user_cart)

@seller.route('/edit-listing/<book_id>', methods=["GET", "POST"])
@login_required 
def edit_listing(book_id):
    title = "Edit Listing"
    book = Book.query.get_or_404(book_id)
    form = BookForm()

    if form.validate_on_submit():
        book.update(**form.data)
        flash(f"{book.title} has been updated.", "warning")
        return redirect(url_for('seller.view_listing'))

    return render_template('edit_listing.html', title = title, book = book, form = form)

app/blueprints/shop/__init__.py
from flask import Blueprint

shop = Blueprint('shop', __name__, url_prefix='/shop')

from . import routes, models

app/blueprints/shop/routes.py
from . import shop 
from flask import render_template, redirect, url_for, flash
from flask_login import login_required, current_user
from app.blueprints.seller.models import Book
from app.blueprints.shop.models import Cart
import random

@shop.route('/')
def index():
    title = 'Home'
    cart = ""
    carousel = []
    carouselboks=""
    if current_user.is_authenticated:
        cart = current_user.my_cart.all()

    books = Book.query.all()
    if len(books)> 0:
        for i in range(3):
            rand = random.randint(0, len(books) -1)
            carousel.append(books[rand])

    
    return render_template('index.html', title=title, cart=cart, carouselbooks = carousel)

@shop.route('/view-cart')
def view_cart():
    title = "Cart"
    user_cart = ""
    books = [Book.query.filter(Book.id == cart.book_id).all()[0] for cart in current_user.my_cart.all()]
    total = sum([book.price for book in books])

    if books:
        cart = current_user.my_cart.all()
        user_cart = zip(books, cart)

    return render_template('view_cart.html', title=title, user_cart = user_cart, total = total)

@shop.route('/store')
def store():
    title = 'Store'
    books = Book.query.all()

    return render_template('store.html', tilte=title, books = books)

@shop.route('/full-item/<item_id>', methods=["GET", "POST"])
@login_required 
def full_item(item_id):
    item = Book.query.get_or_404(item_id)
    title = f"{item} Full Info"

    return render_template('full_item.html', title = title, item = item)

@shop.route('/add-to-cart/<item_id>')
@login_required 
def add_to_cart(item_id):
    item = Book.query.get_or_404(item_id)
    new_cart = Cart(user_id = current_user.id, book_id = item.id)
    flash(f"{item.title} has been added to your cart.", "success")
    return redirect(url_for('shop.store'))

@shop.route('/checkout')
@login_required 
def checkout():
    my_cart = current_user.my_cart.all()
    for cart in my_cart:
        cart.delete()
    flash(f"You have successfully checked out! Your cart is now empty.", "success")
    return redirect(url_for('shop.store'))

@shop.route('/remove-item/<cart_id>')
@login_required 
def remove_item(cart_id):
    cart = Cart.query.get_or_404(cart_id)
    cart.delete()
    flash(f"Removed from your cart.", "info")
    return redirect(url_for('shop.view_cart'))

app/routes.py
from app import app
from flask import redirect, url_for

@app.route('/') 
def index():
    return redirect(url_for('shop.index'))

app/templates/alert_message.html
{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="div alert alert-{{ category }} alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="Description" content="Enter your description here"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <!-- <link rel="stylesheet" href="assets/css/style.css"> -->
        <title>Book Store | {{ title }}</title>
    </head>
    <body class="bg-light" >
        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom border-secondary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('shop.index') }}">Nates Book Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('shop.index') }}">Home</a>
                        <a class="nav-link" href="{{ url_for('shop.store') }}">View Store</a>
                        {% if current_user.is_authenticated %}
                        <a class="nav-link" href="{{ url_for('shop.view_cart') }}">View Your Cart</a>
                        <a class="nav-link" href="{{ url_for('seller.upload_item') }}">Start Selling!</a>
                            {% if current_user.my_listings.all() %}
                            <a class="nav-link" href="{{ url_for('seller.view_listing') }}">View Your Listings</a>
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class="navbar-nav mx-3">
                        {% if current_user.is_authenticated %}
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                        {% else %}
                        <a class="nav-link justify-self-end" href="{{ url_for('auth.signup') }}">Sign Up</a>
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>

        <div class="container">
            {% include 'alert_message.html' %}
            {% block content %}

            {% endblock content %}
        </div>




        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
    </body>
</html>

app/templates/cart.html
{% extends 'base.html' %}

app/templates/edit_listing.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="mt-5">Your current listing looks like this: </h3>
    <div class="container d-flex justify-content-center mt-5">
        <div class="card mb-3" style="max-width: 100%;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ book.image_url }}" class="card-img-top mt-1 p-1" alt="{{ book.title }}">
                    <!-- <img src="..." class="img-fluid rounded-start" alt="..."> -->
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ book.title }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ book.author }}</h6>
                        <p class="card-text">Price $ {{book.price}}</p>
                        <p class="card-text">{{ book.desc }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <h3>If you would like to change anything please enter the new information in the form below.</h3>

    <form method="post" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.title.label }}
            {{ form.title(class="form-control", value=book.title) }}

            {{ form.author.label }}
            {{ form.author(class="form-control", value=book.author) }}

            {{ form.desc.label }}
            {{ form.desc(class="form-control", value=book.desc) }}

            {{ form.price.label }}
            {{ form.price(class="form-control", value=book.price) }}

            {{ form.submit(class="btn btn-primary mt-2") }} 
        </div>

    </form>

{% endblock content %}

app/templates/full_item.html
{% extends 'base.html' %}

{% block content %}
<div class="container d-flex justify-content-center mt-5">

    <div class="card mb-3" style="max-width: 100%;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ item.image_url }}" class="card-img-top mt-1 p-1" alt="{{ item.title }}">
                <!-- <img src="..." class="img-fluid rounded-start" alt="..."> -->
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ item.title }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ item.author }}</h6>
                    <p class="card-text">Price $ {{item.price}}</p>
                    <p class="card-text">{{ item.desc }}</p>
                    <a href="{{ url_for('shop.add_to_cart', item_id=item.id) }}" class="btn btn-success">Add to Cart <i class="fas fa-cart-plus"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
    




{% endblock content %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
  {% if carouselbooks %}
    <div id="landingCarousel" class="carousel slide mt-5" data-bs-ride="carousel">
        <div class="carousel-inner d-flex">
          <div class="carousel-item active">
            <img src="{{ carouselbooks[0].image_url }}" class="d-block" style="margin: auto; height: 50vh; object-fit: cover;" alt="...">                                            
          </div>
          <div class="carousel-item">
            <img src="{{ carouselbooks[1].image_url }}" class="d-block" style="margin: auto; height: 50vh; object-fit: cover;" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{{ carouselbooks[2].image_url }}" class="d-block" style="margin: auto; height: 50vh; object-fit: cover;" alt="...">
          </div>
        </div>
        <button class="carousel-control-prev" style="filter: invert(100)" type="button" data-bs-target="#landingCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" style="filter: invert(100)" type="button" data-bs-target="#landingCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
  {% endif %}  
{% endblock content %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5" >


    <form method="post">
        {{ form.csrf_token }}
        <div class="form-group">

            <div class="container-fluid d-flex justify-content-center">
                <div class="row justify-content-center">
                    <div class="card mb-3 bg-purple">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <img src="https://images.pexels.com/photos/1926988/pexels-photo-1926988.jpeg" class="img-fluid rounded-start my-2" style="max-height: 45vh" alt="...">
                            </div>
                            <div class="col-md-8 d-flex">
                                <div class="card-body my-auto">
                                    <h5 class="card-title">Sign In!</h5>
                                    {{ form.username.label }}
                                    {{ form.username(class="form-control", placeholder="Username") }}
                        
                                    {{ form.password.label }}
                                    {{ form.password(class="form-control", placeholder="Password") }}
                        
                                    {{ form.submit(class="btn btn border-primary primary mt-2") }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </form>
</div>

{% endblock content %}

app/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5" >


    <form method="post">
        {{ form.csrf_token }}
        <div class="form-group">

            <div class="container-fluid d-flex justify-content-center">
                <div class="row justify-content-center">
                    <div class="card mb-3 bg-purple">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <img src="https://images.pexels.com/photos/1926988/pexels-photo-1926988.jpeg" class="img-fluid rounded-start my-2" style="max-height: 45vh" alt="...">
                            </div>
                            <div class="col-md-8 d-flex">
                                <div class="card-body my-auto">
                                    <h5 class="card-title">Sign In!</h5>
                                    {{ form.email.label }}
                                    {{ form.email(class="form-control", placeholder="Email") }}
                        
                                    {{ form.username.label }}
                                    {{ form.username(class="form-control", placeholder="Username") }}
                        
                                    {{ form.password.label }}
                                    {{ form.password(class="form-control", placeholder="Password") }}
                        
                                    {{ form.confirm_password.label }}
                                    {{ form.confirm_password(class="form-control", placeholder="Confirm Password") }}
                        
                                    {{ form.submit(class="btn btn-primary w-100 mt-2") }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </form>
</div>

{% endblock content %}

app/templates/store.html
{% extends 'base.html' %}

{% block content %}

    {% if not books %}
    <div>
        <h2>It seems like the store is currently empty. Consider signing up to add some items for sale or check back later!</h2>
    </div>
    {% endif %}

    <div class="row">
        
    {% for book in books %}
    
        <div class="card m-2" style="width: 18rem;">
            <a data-bs-toggle="modal" data-bs-target="#imgModal{{ book.id }}">
                <img src="{{ book.image_url }}" class="card-img-top mt-1" style="width: 100%; height: 20vh; object-fit: cover;" alt="{{ book.title }}">
            </a>
            <div class="card-body">
                <h5 class="card-title text-truncate">{{ book.title }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ book.author }}</h6>
                <p class="card-text" style="-webkit-line-clamp: 3; display: -webkit-box; -webkit-box-orient: vertical;overflow: hidden;">{{ book.desc }}</p>
                <a href="{{ url_for('shop.full_item', item_id=book.id) }}" class="btn btn-info">More Info</a>
            </div>
        </div>
        
        <!--Scrollable Modal -->
        <div class="modal fade" id="imgModal{{ book.id }}" tabindex="-1" aria-labelledby="imgModal{{ book.id }}" aria-hidden="true">
            <div class="modal-dialog modal-dialog-scrollable">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title text-dark" id="imgModal{{ book.id }}">{{ book.title }}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body text-dark">
                        <img src="{{ book.image_url }}" class="card-img-top" style="width: 100%" alt="...">
                    </div>
                    <div class="modal-footer justify-content-between">
                        <a href="{{ url_for('shop.add_to_cart', item_id=book.id) }}" class="btn btn-success">Add to Cart <i class="fas fa-cart-plus"></i></a>
                        <!-- <button type="button" class="btn btn-success" data-bs-dismiss="modal"></button> -->
                        <a href="{{ url_for('shop.full_item', item_id=book.id) }}" class="btn btn-info">More Info</a>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    
    {% endfor %}
    </div>





{% endblock content %}

app/templates/upload_item.html
{% extends 'base.html' %}

{% block content %}

    <h2>Add a book to your personal store.</h2>

    <form method="post" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div class="form-group">
            <p>Add an image: </p>
            {{ form.image }}

            {{ form.title.label }}
            {{ form.title(class="form-control", placeholder="Title") }}

            {{ form.author.label }}
            {{ form.author(class="form-control", placeholder="Author") }}

            {{ form.desc.label }}
            {{ form.desc(class="form-control", placeholder="Description") }}

            {{ form.price.label }}
            {{ form.price(class="form-control", placeholder="$") }}

            {{ form.submit(class="btn btn-primary w-100 mt-2") }} 

        </div>

    </form>


{% endblock content %}

app/templates/view_cart.html
{% extends 'base.html' %}

{% block content %}
<div class="container d-flex">
    {% if not user_cart %}
        <p>Your cart seems to be empty, consider adding to it <a href="{{ url_for('shop.store') }}">here!</a></p>
    {% else %}
    <div class="card-group col-7 flex-column mt-2">
        {% for book, cart in user_cart %}
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ book.image_url }}" class="img rounded p-2" style="max-height: 15vh" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body d-flex flex-column justify-content-between h-100">
                        <div class="row">
                            <h5 class="card-title">{{ book.title }}</h5>
                        </div>
                        <div class="row">
                            <p class="card-text">${{ book.price }}</p>
                        </div>
                        <div class="row justify-content-end mx-3">
                            <a href="{{ url_for('shop.remove_item', cart_id=cart.id) }}" class="btn btn-danger" style="width: 50px;"><i class="fas fa-trash-alt"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        {% endfor %}
    </div>

    {% endif %}

    <div class="container col-4">

        <p>Total ${{ total }}</p>
        <p>Payment stuff</p>
        <p>Shipping stuff</p>
        <p>stuff</p>

        <a href="{{ url_for('shop.checkout') }}" class="btn btn-success">Checkout</a>

    </div>
</div>


{% endblock content %}

app/templates/view_listing.html
{% extends 'base.html' %}

{% block content %}

    <div class="card-group col-7 flex-column mt-2">
        {% for book, cart in user_cart %}
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ book.image_url }}" class="img rounded p-2" style="max-height: 15vh" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body d-flex flex-column justify-content-between h-100">
                        <div class="row">
                            <h5 class="card-title">{{ book.title }}</h5>
                        </div>
                        <div class="row">
                            <p class="card-text">${{ book.price }}</p>
                        </div>
                        <div class="row justify-content-between mx-3">
                            <a href="{{ url_for('seller.edit_listing', book_id=book.id) }}" class="btn btn-success" style="width: 50px;"><i class="fas fa-edit"></i></a>
                            <a href="{{ url_for('shop.index') }}" class="btn btn-danger" style="width: 50px;"><i class="fas fa-trash-alt"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        {% endfor %}
    </div>

{% endblock content %}